org.gradle.jvmargs = -Xmx6G
org.gradle.java.installations.auto-download=false
org.gradle.java.installations.paths=C:/Program Files/Zulu/zulu-17,C:/Program Files/Zulu/zulu-21
org.gradle.java.home=C:/Program Files/Zulu/zulu-21
org.gradle.parallel = true
org.gradle.caching = true

# Mod Info
mod_id = gtceu
mod_name = GregTech
mod_version = 7.5.0
mod_description = BingoTech Fork - GregTech CEu: Modern, built for the BingoTech modpack
mod_license = LGPL-3.0 license
mod_url = https://github.com/Bingo-888/GregTech-Modern/
mod_issue_tracker = https://github.com/Bingo-888/GregTech-Modern/issues/
maven_group = com.gregtechceu.gtceu
